### ISSUE TITLE
Chairperson December 2024 - March 2025

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/foundation#20]
I am looking for volunteers for the next chair person. Anyone? :)

Maybe someone that hasn't chaired yet? :) But no must, of course.

**Comment by yang-ruoxi** [comment]
happy to volunteer if others are unavailable!

**Comment by JaGeo** [comment]
Awesome! Thanks. I will add you as a chair person 😀

**Comment by rkingsbury** [comment]
Thanks @yang-ruoxi ! I'll also remind everyone that although I am currently listed for Aug-Nov, I'd be happy to defer to someone else who has not chaired before. (In fact, I have some personal reasons why it would be nice not to chair at that time). Would you be interested in swapping positions, Ruoxi?

**Comment by yang-ruoxi** [comment]
sure @rkingsbury  I can swap with you!

**Comment by JaGeo** [comment]
Okay, great. I will switch the order then.

**Comment by rkingsbury** [comment]
> sure @rkingsbury I can swap with you!

Thanks Ruoxi!
